name: Main

on: [push, pull_request]

jobs:

  lint:
    name: Lint
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: .reports/coverage/cobertura.xml
          fail_ci_if_error: true
