name: Main

on: [push, pull_request]

jobs:

  ci:
    name: CI
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - name: Setup environment
        run: make setup
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: .reports/coverage/cobertura.xml
          fail_ci_if_error: true
      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: .reports
          if-no-files-found: error

  build:
    name: Build
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: pip install --upgrade pip build wheel check-wheel-contents
      - name: Build package
        run: poetry build
      - name: Check wheel contents
        run: check-wheel-contents dist/*.whl
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
          if-no-files-found: error
